# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Git-Repositories-Search' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Git-Repositories-Search
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Moya'
    pod 'Kingfisher'
    pod 'PromiseKit'


  target 'Git-Repositories-SearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Git-Repositories-SearchUITests' do
    # Pods for testing
  end

end
